<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Xtreamium.Proxy</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.4" />
    <PackageReference Include="Quartz.AspNetCore" Version="3.8.1" />
    <PackageReference Include="Quartz.Extensions.Hosting" Version="3.8.1" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Data\quartz.sql" />
    <EmbeddedResource Include="Data\quartz.sql" />
  </ItemGroup>

</Project>
