services:
  windows:
    image: dockurr/windows
    container_name: xtreamium-windows-tiny11
    environment:
      VERSION: "tiny11"
      USERNAME: "admin"
      PASSWORD: "password"
      LANGUAGE: "English"
      REGION: "en-IE"
      TIMEZONE: "GMT Standard Time"
      KEYBOARD: "en-IE"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8011:8006
      - 3394:3389/tcp
      - 3394:3389/udp
    stop_grace_period: 2m
    restart: on-failure
    volumes:
      - ./storage:/storage
